services:
  # Front Page Development (for local development only)
  front-page-dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./front-page:/app
      - front_page_node_modules:/app/node_modules
    ports:
      - "4321:4321"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development
    profiles:
      - dev

  # Front Page Production
  front-page-prod:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        APP_NAME: front-page
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - internal
    # No external ports exposed - cloudflared connects internally on port 80

  # Documentation Site Development (for local development only)
  docs-site-dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./docs-site:/app
      - docs_site_node_modules:/app/node_modules
    ports:
      - "4322:4321"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development
    profiles:
      - dev

  # Documentation Site Production
  docs-site-prod:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        APP_NAME: docs-site
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - internal
    # No external ports exposed - cloudflared connects internally on port 80

  # Single Cloudflare Tunnel for all services
  # Configure in Cloudflare dashboard:
  # - for-the-gg.org → http://front-page-prod:80
  # - docs.for-the-gg.org → http://docs-site-prod:80
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - internal
    depends_on:
      - front-page-prod
      - docs-site-prod

networks:
  internal:
    driver: bridge

volumes:
  front_page_node_modules:
  docs_site_node_modules: